# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: audit/v1/audit.proto for package 'rails.core.audit.v1'

require 'grpc'
require_relative 'audit_pb'

module Rails
  module Core
    module Audit
      module V1
        module AuditService
          # Unary ingest: exactly one event per request (v1).
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'rails.core.audit.v1.AuditService'

            rpc :AppendAuditEvent, ::Rails::Core::Audit::V1::AppendAuditEventRequest, ::Rails::Core::Audit::V1::AppendAuditEventResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
